model_name: llama
model_type: llama3
model_path: meta-llama/Meta-Llama-3-8B-Instruct

attack_type: DPO+KE
edit_method: rome
edit_hparams_path: /home/jtj/EditAgents/config/editing/rome/llama3-8b.yaml

role_file: /home/jtj/EditAgents/data/million_villagers_1024.json
dataset_path:  /home/jtj/EditAgents/data/counterfact/counterfact-edit-1k.json
history_dir: /home/jtj/EditAgents/history/llama3/zsre_mend_train-harmful-1k/attack_with_rlhf_10000
lora_path: /home/jtj/outputs/checkpoint
num_of_agents: 5
num_of_edited_agents: 1
communication_turns: 3
max_new_tokens: 120
max_history_tokens: 15000

device: 0,1
model_parallel: True
